services:
  api:
    build:
      context: .
      dockerfile: src/TurnOS.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TurnOS;User=sa;Password=YourPassword123!;TrustServerCertificate=true;
      - Jwt__Key=TuClaveSecretaDe32CaracteresMin!!
      - Jwt__Issuer=TurnOS
      - Jwt__Audience=TurnOS
      - Jwt__ExpirationMinutes=60
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourPassword123!' -Q 'SELECT 1' -C -b"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  sqldata:
